name: GoopDropToContainer
version: '1.0-SNAPSHOT'
main: me.sentryoz.goopDropToContainer.GoopDropToContainer
api-version: '1.20'
depend: [Gunging_Ootilities_Plugin]
softdepend: [MMOItems]
commands:
  addcontainer:
    description: Adds a bag with a specified type.
    usage: /addcontainer <bag_name> <items_type> <priority>

  removecontainer:
    description: Removes a bag.
    usage: /removecontainer <bag_name>
